### ISSUE TITLE
Default font cache

### ISSUE THREAD

**Issue by rgeronimi** [llgcode/draw2d#121]
In font.go, the default font cache stored in the global variable fontCache is not synchronized. Consequently, any program performing concurrent drawings in separate goroutines is exposed to potential data races. Plus the program is exposed to future crashes with new versions of the golang compiler, as the golang spec doesn't guarantee how maps should behave in case of concurrent reads and writes.

This may be resolved by documenting it (i.e., pushing the need for synchronization onto the library client) or using a sync.Mutex in font.go.

**Comment by redstarcoder** [comment]
The same issue is encountered with `glyphCache` in `draw2dbase/text.go`.

If we do use a mutex in the library, I would recommend a `RWMutex` at least for `glyphCache` (I haven't really looked into what `fontCache` is doing) as once the cache is built, it doesn't do (m)any writes anyways.

**Comment by redstarcoder** [comment]
I'm more in favour of documenting that it's not synchronized as realistically how often are you going to have multiple coroutines/threads processing text? I think it should be up to the user to make sure it's safe.

Unless there's no noticable performance penalty. The font routines aren't super duper fast, and slowing them down further doesn't seem worth it.

**Comment by redstarcoder** [comment]
So I looked into this more. `fontCache` is an interface `FontCache` that contains `Store` and `Load`. Currently you could just set your own cache that is synchronized. This issue is mostly about the default variable `defaultFonts` and the struct `defaultFontCache` as by default, it doesn't synchronize the `Store` and `Load` methods.

So we really just need to make it clear that it isn't synchronized by default, and that's it I think.

**Comment by rgeronimi** [comment]
Looks good to me

**Comment by llgcode** [comment]
Ok thanks for your comments, I close the issue.

**Comment by rgeronimi** [comment]
I made a mistake when I wrote "Looks good to me": it's entirely fine to let FontCache as is, as a lib user can replace it with a synchronized version. But glyphCache provides no similar mechanism : it's entirely private so a lib user has no way to replace it with a synchronized version. Second, given that it's called for every glyph drawn, synchronization errors may indeed occur in image web servers, requiring only moderate traffic.

**Comment by gerald1248** [comment]
@rgeronimi that's my take on the issue exactly. I'm now switching to a fork of draw2d just so I can add a setGlyphCache method.

@redstarcoder asked why anyone would need parallel text drawing, but I'm building a simple image server exactly as you suggest and not using a goroutine because of the shared glyphCache seems wrong.

**Comment by gerald1248** [comment]
Will share PR when done

**Comment by gerald1248** [comment]
Still WIP because the problem seems to run a bit deeper.

Even if we disable the glyphCache altogether...

```
func FetchGlyph(gc draw2d.GraphicContext, fontName string, chr rune) *Glyph {
  return renderGlyph(gc, fontName, chr)
}
```

...building with -race identifies potential race conditions.

@llgcode Your reply to #122 suggests this may not be fixable. Do you know how far we'd need to dig (into the font handling mechanism) to address this?

**Comment by llgcode** [comment]
Hi @gerald1248,
we should use draw2d in multiple routine if we use one gc for each gc. If we have trouble with global fontcache we need to fix it. Where does it fails ? Do you have a test that show a problem?

**Comment by gerald1248** [comment]
Thankfully it's easily repeatable (with flag -race my build always runs into problems as I write out a bunch of sample images as part of the build). I will prepare a test case.

**Comment by redstarcoder** [comment]
@llgcode,  I'll look into making the `fontCache` replacable in the same style as the other globals. I just have a bit of work in other projects first, but I can probably get to it this week.
